name: Generate Tests for PR

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'app/**/*.py'
      - 'run.py'

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set up Ollama and DeepSeek-R1
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          sudo systemctl start ollama || ollama serve &
          sleep 5  # Give Ollama some time to start
          ollama pull deepseek-r1

      - name: Generate tests based on changed files
        run: |
          python .github/scripts/generate_tests.py

      - name: Commit and push generated tests
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add tests/
          git commit -m "Auto-generate tests for PR changes" || echo "No changes to commit"
          git push
